# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: androidCI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [29]
        target: [default]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java_version: 1.8
    - uses: action/setup-node@master
      with:
        node-version: '14'
    - run: |
            npm install -g appium@v1.21.0
            appium -v
            appium &>/dev/null &
    - name: Run Appium Test
      uses: reactivecircus/android-emulator-runner@v1
      with:
           api-level: ${{ matrix.api-level }}
           target: ${{ matrix.target }}
           arch: x86_64
           profile: pixel_2
           script: mvn clean test -Pandroid
           
